[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "npm i -g pnpm && npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
